document.writeln("<div class=\'nav\'>");
document.writeln("			<ul class=\'select_business\' >");
document.writeln("			<li class=\'ChinaMobile\'>中国移动</li>	");
document.writeln("			  <li>中国联通</li>	");
document.writeln("				<li>中国电信</li>");
document.writeln("				<span class='line'></span>");
document.writeln("			</ul>");
document.writeln("			<div class=\'selectStyle\'>	");
document.writeln("				<select  id=\'aaa\' value=\'\' class=\'select_city\'>");
document.writeln("				  <option value =\'南宁市\'>南宁市</option>");
document.writeln("				  <option value =\'柳州市\'>柳州市</option>");
document.writeln("				  <option value=\'桂林市\'>桂林市</option>");
document.writeln("				  <option value=\'梧州市\'>梧州市</option>");
document.writeln("				  <option value=\'北海市\'>北海市</option>");
document.writeln("				  <option value=\'防城港市\'>防城港市</option>");
document.writeln("				  <option value=\'钦州市\'>钦州市</option>");
document.writeln("				  <option value=\'贵港市\'>贵港市</option>");
document.writeln("				  <option value=\'玉林市\'>玉林市</option>");
document.writeln("				  <option value=\'百色市\'>百色市</option>");
document.writeln("				  <option value=\'贺州市\'>贺州市</option>");
document.writeln("				  <option value=\'河池市\'>河池市</option>");
document.writeln("				  <option value=\'来宾市\'>来宾市</option>");
document.writeln("				  <option value=\'崇左市\'>崇左市</option>");
document.writeln("				  <option value=\'岑溪市\'>岑溪市</option>");
document.writeln("				  <option value=\'东兴市\'>东兴市</option>");
document.writeln("				  <option value=\'桂平市\'>桂平市</option>");
document.writeln("				  <option value=\'北流市\'>北流市</option>");
document.writeln("				  <option value=\'靖西市\'>靖西市</option>");
document.writeln("				  <option value=\'宜州市\'>宜州市</option>");
document.writeln("				  <option value=\'合山市\'>合山市</option>");
document.writeln("				  <option value=\'凭祥市\'>凭祥市</option>");
//document.writeln("				  <option value=\'杭州市\'>杭州市</option>");
document.writeln("				</select>");
document.writeln("			</div>");
document.writeln("		</div>");